# Generated by Django 5.1.3 on 2024-11-27 18:56

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=35)),
                ('model', models.CharField(max_length=35)),
                ('category', models.CharField(max_length=35)),
                ('release_year', models.DateField()),
                ('model_year', models.DateField()),
                ('fuel', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('doors', models.IntegerField()),
                ('quilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=15)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.models.Car.upload_image_customer)),
            ],
        ),
    ]
